### ISSUE TITLE
Exercise 4: fix problems installing light-meter 

### ISSUE THREAD

**Issue by ezodude** [CardboardIoT/smart-pinhole-workshop#6]
When installed globally, verifying the exercise threw an error saying it cannot find module.

NPM installing it locally worked.

It should just be installed globally.

**Comment by andrewn** [comment]
I don't think you can require a globally installed node module. So this is expected behaviour when `require('lightmeter')` is called. [More info](http://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package).

Whilst we could do something in the lightmeter server code and binary to make the `lightmeter` node module available, I think that might be more confusing since this would magic behaviour for this node module only and wouldn't apply to others such as the MQTT module.

**Comment by ezodude** [comment]
Makes sense. I'll update the documentation.

**Comment by ezodude** [comment]
Updated relevant Problem.mds.
